fix(dbapi): autocommit enabling fails if no transactions begun (#177)
* fix(dbapi): autocommit enabling fails if no transactions begun

* remove unused import

* don't calculate checksums in autocommit mode

* try using dummy WHERE clause

* revert where clause

* unveil error

* fix where clauses

* add print

* don't log

* print failed exceptions

* don't print

* separate insert statements

* don't return

* re-run

* don't pyformat insert args

* args

* re-run

* fix

* fix error in transactions.tests.NonAutocommitTests.test_orm_query_without_autocommit

* fix "already committed" error

* fix for AttributeError: 'tuple' object has no attribute 'items'

* fix

* fix KeyError: 'type'

Co-authored-by: Chris Kleinknecht <libc@google.com>
Co-authored-by: larkee <31196561+larkee@users.noreply.github.com>
Co-authored-by: Alex <7764119+AVaksman@users.noreply.github.com>