chore(spanner): remove --builtin=gettext from samples flake8 args (#18444)
`pyflakes 4.0.0` (pulled in by `flake8 7.4.0`) removed the class-level
`Checker.builtIns` attribute on `pyflakes.checker.Checker` in favor of
an instance attribute initialized in `Checker.__init__`. Passing
`--builtin=gettext` to `flake8 7.4.0` causes
`FlakesChecker.parse_options` to crash with `AttributeError: type object
'FlakesChecker' has no attribute 'builtIns'`.

Remove the unused `--builtin=gettext` flag from `FLAKE8_COMMON_ARGS` in
`packages/google-cloud-spanner/samples/samples/noxfile.py` so sample
lint sessions succeed with `flake8 7.4.0` and `pyflakes 4.0.0`.

Thank you for opening a Pull Request! Before submitting your PR, there
are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a
[bug/issue](https://github.com/googleapis/google-cloud-python/issues)
before writing your code! That way we can discuss the change, evaluate
designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕