chore(librarian): fix generation for google-cloud-common (#14611)
This fixes the following stack trace with generation for
`google-cloud-common` which caused generation to fail

```
2025-10-01 16:23:35,628 synthtool [WARNING] > No replacements made in packages/google-cloud-common/docs/index.rst for pattern API Reference
-------------
.. toctree::
    :maxdepth: 2

    common/services_
    common/types_
, maybe replacement is no longer needed?
2025-10-01 16:23:35,628 synthtool [WARNING] > No replacements made in packages/google-cloud-common/docs/index.rst for pattern API Reference
-------------
.. toctree::
    :maxdepth: 2

    common/services_
    common/types_
, maybe replacement is no longer needed?
README.rst
Skipping: docs/index.rst
docs/summary_overview.md
Traceback (most recent call last):
  File "/app/./cli.py", line 535, in handle_generate
    _run_post_processor(output, library_id)
  File "/app/./cli.py", line 300, in _run_post_processor
    python_mono_repo.owlbot_main(path_to_library)
  File "/usr/local/lib/python3.9/site-packages/synthtool/languages/python_mono_repo.py", line 329, in owlbot_main
    apply_client_specific_post_processing(
  File "/usr/local/lib/python3.9/site-packages/synthtool/languages/python_mono_repo.py", line 213, in apply_client_specific_post_processing
    assert (
AssertionError: Replaced 0 rather than 1 instances

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./cli.py", line 1406, in <module>
    args.func(
  File "/app/./cli.py", line 538, in handle_generate
    raise ValueError("Generation failed.") from e
ValueError: Generation failed.
```