dbapi: classify every CREATE as updating DDL
Previously, when running

    python3 manage.py migrate

We'd get

        raise ProgrammingError(e.details if hasattr(e, 'details') else e)
        django.db.utils.ProgrammingError: 400 Statement not supported:
        CreateIndexStatement [at 1:1]\nCREATE UNIQUE INDEX
        django_content_type_app_label_model_76bd3d3b_uniq ON djan...\n^

but the error resulted from

        CREATE UNIQUE INDEX

not being recognized as a DDL update.

Every CREATE statement is a DDL update, so this change recognizes
every `CREATE|DROP|ALTER` as DDL statements, which they are.