fix: fix mypy errors in google-cloud-monitoring-dashboards/google/monitoring (#15493)
Towards https://github.com/googleapis/google-cloud-python/issues/15104

This is needed to unblock
https://github.com/googleapis/google-cloud-python/pull/15457 . See the
following mypy failure for `google-cloud-monitoring-dashboards`

See follow up issue
https://github.com/googleapis/google-cloud-python/issues/11858 to remove
the `google/monitoring` folder which is no longer being generated
automatically.

See follow up issue
https://github.com/googleapis/proto-plus-python/issues/558 for the
`prerelease` presubmit failure.

```
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/types/service.py:19: error: Name "proto" is not defined  [name-defined]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/types/drilldowns.py:19: error: Name "proto" is not defined  [name-defined]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/base.py:49: error: Incompatible default for argument "credentials" (default has type "None", argument has type "Credentials")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/base.py:49: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/base.py:49: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:52: error: Incompatible default for argument "credentials" (default has type "None", argument has type "Credentials")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:52: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:52: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:53: error: Incompatible default for argument "credentials_file" (default has type "None", argument has type "str")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:53: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:53: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:54: error: Incompatible default for argument "scopes" (default has type "None", argument has type "Sequence[str]")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:54: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:54: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:56: error: Incompatible default for argument "api_mtls_endpoint" (default has type "None", argument has type "str")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:56: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:56: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:57: error: Incompatible default for argument "client_cert_source" (default has type "None", argument has type "Callable[[], tuple[bytes, bytes]]")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:57: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:57: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:97: error: Incompatible types in assignment (expression has type "bool", variable has type "Credentials")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:115: error: Function "client_cert_source" could always be true in boolean context  [truthy-function]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:148: error: Incompatible default for argument "credentials" (default has type "None", argument has type "Credentials")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:148: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:148: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:149: error: Incompatible default for argument "credentials_file" (default has type "None", argument has type "str")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:149: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc.py:149: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:54: error: Incompatible default for argument "credentials" (default has type "None", argument has type "Credentials")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:54: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:54: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:95: error: Incompatible default for argument "credentials" (default has type "None", argument has type "Credentials")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:95: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:95: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:99: error: Incompatible default for argument "api_mtls_endpoint" (default has type "None", argument has type "str")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:99: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/transports/grpc_asyncio.py:99: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/client.py:474: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:55: error: Argument 1 to "get_transport_class" of "DashboardsServiceClientMeta" has incompatible type "type[type[DashboardsServiceClient]]"; expected "DashboardsServiceClientMeta"  [arg-type]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:61: error: Incompatible default for argument "credentials" (default has type "None", argument has type "Credentials")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:61: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:61: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:63: error: Module "google.api_core.client_options" is not valid as a type  [valid-type]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:63: note: Perhaps you meant to use a protocol matching the module structure?
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:103: error: Incompatible default for argument "request" (default has type "None", argument has type "CreateDashboardRequest")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:103: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:103: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:105: error: Incompatible default for argument "retry" (default has type "_MethodDefault", argument has type "Retry")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:106: error: Incompatible default for argument "timeout" (default has type "None", argument has type "float")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:106: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:106: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:164: error: Incompatible default for argument "request" (default has type "None", argument has type "ListDashboardsRequest")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:164: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:164: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:166: error: Incompatible default for argument "retry" (default has type "_MethodDefault", argument has type "Retry")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:167: error: Incompatible default for argument "timeout" (default has type "None", argument has type "float")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:167: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:167: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:234: error: Incompatible default for argument "request" (default has type "None", argument has type "GetDashboardRequest")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:234: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:234: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:236: error: Incompatible default for argument "retry" (default has type "_MethodDefault", argument has type "Retry")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:237: error: Incompatible default for argument "timeout" (default has type "None", argument has type "float")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:237: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:237: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:295: error: Incompatible default for argument "request" (default has type "None", argument has type "DeleteDashboardRequest")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:295: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:295: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:297: error: Incompatible default for argument "retry" (default has type "_MethodDefault", argument has type "Retry")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:298: error: Incompatible default for argument "timeout" (default has type "None", argument has type "float")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:298: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:298: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:345: error: Incompatible default for argument "request" (default has type "None", argument has type "UpdateDashboardRequest")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:345: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:345: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:347: error: Incompatible default for argument "retry" (default has type "_MethodDefault", argument has type "Retry")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:348: error: Incompatible default for argument "timeout" (default has type "None", argument has type "float")  [assignment]
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:348: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
.nox/mypy-3-14/lib/python3.14/site-packages/google/monitoring/dashboard_v1/services/dashboards_service/async_client.py:348: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
```