chore(librarian): update exception and valid namespaces (#14458)
This fixes the following issue which caused
https://github.com/googleapis/google-cloud-python/pull/14457 to fail
with `Generation failed for google-cloud-video-live-stream`

```
ValueError: Build failed.
    raise ValueError("Build failed.") from e
  File "/app/./cli.py", line 601, in handle_build
    args.func(librarian=args.librarian, repo=args.repo)
  File "/app/./cli.py", line 1014, in <module>
Traceback (most recent call last):
The above exception was the direct cause of the following exception:
ValueError: The namespace `google.cloud.video` for `google-cloud-video-live-stream` must be one of ['google', 'google.apps', 'google.ads', 'google.cloud', 'google.maps', 'google.shopping', 'google.cloud.billing'].
    raise ValueError(
  File "/app/./cli.py", line 546, in _verify_library_namespace
    _verify_library_namespace(library_id, repo)
  File "/app/./cli.py", line 597, in handle_build
Traceback (most recent call last):
```