chore(librarian): add support for `librarian generate -build` for split repos (#14871)
This PR resolves the following error when running `librarian generate
-build` in a split repository. See the output for
[python-pubsub](https://github.com/googleapis/python-pubsub) below.

```
time=2025-11-12T15:43:16.709Z level=INFO msg="=== Docker end ================================================================="
time=2025-11-12T15:43:16.710Z level=INFO msg="cleaning directories" "source roots"=[.]
time=2025-11-12T15:43:16.731Z level=INFO msg="copying library files" id=google-cloud-pubsub destination=/usr/local/google/home/partheniou/git/python-pubsub source=/tmp/librarian-2928727914/output/google-cloud-pubsub
time=2025-11-12T15:43:16.789Z level=INFO msg="generation succeeds" id=google-cloud-pubsub
time=2025-11-12T15:43:16.789Z level=INFO msg="performing build for library" id=google-cloud-pubsub
time=2025-11-12T15:43:16.790Z level=INFO msg="=== Docker start ==============================================================="
time=2025-11-12T15:43:16.790Z level=INFO msg="/usr/bin/docker run --rm -v /usr/local/google/home/partheniou/git/python-pubsub/.librarian:/librarian -v /usr/local/google/home/partheniou/git/python-pubsub:/repo --user 814163:89939 us-central1-docker.pkg.dev/cloud-sdk-librarian-prod/images-prod/python-librarian-generator:latest build --librarian=/librarian --repo=/repo"
time=2025-11-12T15:43:16.790Z level=INFO msg=--------------------------------------------------------------------------------
2025-11-12 15:43:17,540 synthtool [CRITICAL] > You are running the synthesis script directly, this will be disabled in a future release of Synthtool. Please use python3 -m synthtool instead.
2025-11-12 15:43:17,725 synthtool [DEBUG] > Using local templates at /synthtool/synthtool/gcp/templates
2025-11-12 15:43:17,731 synthtool [DEBUG] > Using local templates at /synthtool/synthtool/gcp/templates
Traceback (most recent call last):
  File "/app/./cli.py", line 1090, in handle_build
    _verify_library_namespace(library_id, repo)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/app/./cli.py", line 1016, in _verify_library_namespace
    raise ValueError(f"Error: Path is not a directory: {library_path}")
ValueError: Error: Path is not a directory: /repo/packages/google-cloud-pubsub

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./cli.py", line 1593, in <module>
    args.func(librarian=args.librarian, repo=args.repo)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./cli.py", line 1094, in handle_build
    raise ValueError("Build failed.") from e
ValueError: Build failed.
time=2025-11-12T15:43:18.097Z level=INFO msg="=== Docker end ================================================================="
time=2025-11-12T15:43:18.097Z level=INFO msg="restoring uncommitted changes" paths=.
time=2025-11-12T15:43:18.151Z level=INFO msg="cleaning untracked files" paths=.
time=2025-11-12T15:43:18.200Z level=ERROR msg="failed to generate library" id=google-cloud-pubsub err="exit status 1"
time=2025-11-12T15:43:18.200Z level=INFO msg="generation statistics" all=1 successes=0 skipped=0 failures=1
time=2025-11-12T15:43:18.200Z level=ERROR msg="librarian command failed" err="all 1 libraries failed to generate (skipped: 0)"
```