chore(librarian): update gapic-generator to 1.30.5 (#15486)
This PR is needed to address the following failure in PR
https://github.com/googleapis/google-cloud-python/pull/15458 when
attempting to enable the `mypy` presubmit.


```
.nox/mypy-3-14/lib/python3.14/site-packages/google/cloud/compute_v1beta/services/wire_groups/transports/base.py:88: error: Name "Any" is not defined  [name-defined]
.nox/mypy-3-14/lib/python3.14/site-packages/google/cloud/compute_v1beta/services/wire_groups/transports/base.py:88: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Any")
.nox/mypy-3-14/lib/python3.14/site-packages/google/cloud/compute_v1beta/services/vpn_tunnels/transports/base.py:88: error: Name "Any" is not defined  [name-defined]
```

See https://github.com/googleapis/gapic-generator-python/pull/2536 for
more details