fix: `update_column_spec` typo in TablesClient docstring (#18)
The docstring contains the non-existent function `update_column_specs`, and fixed it to` update_column_spec` which I think is more appropriate.

The code cause AttributeError: 'TablesClient' object has no attribute 'update_column_specs'.

Fixes #17 🦕