dbapi: raise InterfaceError instead of Error, on closed cursor use
Follow PostgreSQL's psycopg2 adapter by returning
InterfaceError instead of Error when using a closed cursor.
Also while here, unified the message to match psycopg2's, from

    attempting to use an already closed connection

to

    cursor already closed

and for equivalent code for psycopg2:

```python
import psycopg2

def main():
    with psycopg2.connect('user=emmanuelodeke dbname=postgres') as conn:
        cur = conn.cursor()
        cur.execute('SELECT 1')
        print(cur.fetchall())
        cur.close()
        cur.execute('SELECT 1')
        print(cur.fetchall())
```
which prints:

```shell
[(1,)]
Traceback (most recent call last):
  File "postgresql.py", line 29, in <module>
    main()
  File "postgresql.py", line 11, in main
    cur.execute('SELECT 1')
psycopg2.InterfaceError: cursor already closed
```

and in spanner.dbapi

```python
from spanner.dbapi import connect

def main():
    with connect(instance='django-tests', database='db1', project='orijtech-161805', autocommit=True) as conn:
        cur = conn.cursor()
        cur.execute('SELECT 1')
        print(cur.fetchall())
        cur.close()
        cur.execute('SELECT * from tx1')
        print(cur.fetchall())
```

which prints
```shell
[(1,)]
Traceback (most recent call last):
  File "closed.py", line 15, in <module>
    main()
  File "closed.py", line 11, in main
    cur.execute('SELECT * from tx1')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spanner/dbapi/autocommit_on_cursor.py", line 38, in execute
    self._raise_if_already_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spanner/dbapi/base_cursor.py", line 74, in _raise_if_already_closed
    raise InterfaceError('cursor already closed')
spanner.dbapi.exceptions.InterfaceError: cursor already closed
```

Fixes #342