fix: Resolve AttributeError 'Credentials' object has no attribute 'universe_domain' (#739)
* fix: Resolve AttributeError 'Credentials' object has no attribute 'universe_domain'

fix: Add google-auth as a direct dependency

fix: Add staticmethod decorator to methods added in v1.14.0

chore: Update gapic-generator-python to v1.14.1
PiperOrigin-RevId: 603728206

Source-Link: https://github.com/googleapis/googleapis/commit/9063da8b4d45339db4e2d7d92a27c6708620e694

Source-Link: https://github.com/googleapis/googleapis-gen/commit/891c67d0a855b08085eb301dabb14064ef4b2c6d
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiODkxYzY3ZDBhODU1YjA4MDg1ZWIzMDFkYWJiMTQwNjRlZjRiMmM2ZCJ9

* 🦉 Updates from OwlBot post-processor

See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md

---------

Co-authored-by: Owl Bot <gcf-owl-bot[bot]@users.noreply.github.com>
Co-authored-by: Lingqing Gan <lingqing.gan@gmail.com>