chore(librarian): fix generation for google-cloud-compute (#14612)
This PR resolves the following stack trace when generating
google-cloud-compute

```

Traceback (most recent call last):
  File "/app/./cli.py", line 532, in handle_generate
    _generate_api(api_path, library_id, source, output, version)
  File "/app/./cli.py", line 761, in _generate_api
    py_gapic_config = _read_bazel_build_py_rule(api_path, source)
  File "/app/./cli.py", line 556, in _read_bazel_build_py_rule
    result = parse_googleapis_content.parse_content(content)
  File "/app/parse_googleapis_content.py", line 133, in parse_content
    sl.eval(mod, ast, glb, sl.FileLoader(load))
starlark.StarlarkError: error: Variable `exports_files` not found
 --> BUILD.bazel:6:1
  |
6 | exports_files(glob(include = ["*grpc_service_config.json"]))
  | ^^^^^^^^^^^^^
  |


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./cli.py", line 1406, in <module>
    args.func(
  File "/app/./cli.py", line 538, in handle_generate
    raise ValueError("Generation failed.") from e
ValueError: Generation failed.
```