chore(librarian): Add exception namespaces for googleapis-common-protos (#14598)
This PR fixes the following error when running `librarian generate
--build` for a `proto-only` library such as `googleapis-common-protos`

```
Traceback (most recent call last):
  File "/app/./cli.py", line 977, in handle_build
    _verify_library_namespace(library_id, repo)
  File "/app/./cli.py", line 913, in _verify_library_namespace
    raise ValueError(
ValueError: Error: namespace cannot be determined for googleapis-common-protos. Library is missing a `gapic_version.py`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./cli.py", line 1404, in <module>
    args.func(librarian=args.librarian, repo=args.repo)
  File "/app/./cli.py", line 981, in handle_build
    raise ValueError("Build failed.") from e
ValueError: Build failed.
time=2025-09-30T09:00:03.583Z level=INFO
```