fix: remove setup.cfg configuration for creating universal wheels (#13659)
The file `setup.cfg` contains a setting to create a Universal Wheel
which is only needed if libraries support both Python 2 and Python 3.
Python Cloud Client Libraries only support Python 3 so this setting is
no longer needed. See
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#wheels.

This will resolve the following warning in [this build
log](https://github.com/googleapis/google-cloud-python/actions/runs/13822574147/job/38671145919?pr=13644)
from PR https://github.com/googleapis/google-cloud-python/pull/13644:

```
Building wheels for collected packages: googleapis-common-protos
  Building wheel for googleapis-common-protos (pyproject.toml): started
  Building wheel for googleapis-common-protos (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for googleapis-common-protos (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40349 lines of output]
      running bdist_wheel
      /tmp/pip-build-env-9o_3w17v/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py:135: SetuptoolsDeprecationWarning: bdist_wheel.universal is deprecated
      !!
      
              ********************************************************************************
              With Python 2.7 end-of-life, support for building universal wheels
              (i.e., wheels that support both Python 2 and Python 3)
              is being obviated.
              Please discontinue using this option, or if you still need it,
              file an issue with pypa/setuptools describing your use case.
      
              By 2025-Aug-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************
      
      !!
```